### ISSUE TITLE
Upgrade Cypress to 5.3.0

### ISSUE THREAD

**Issue by KevinBusch** [AndcultureCode/AndcultureCode.JavaScript.Core#71]
When upgrading to Cypress 5.3.0, `npm install` is failing to install something correctly.   

``` javascript
/home/travis/build/AndcultureCode/AndcultureCode.JavaScript.Core/node_modules/cypress/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
} catch {

SyntaxError: Unexpected token {
```

For full error, see slack screenshot here.
https://files.slack.com/files-pri/T028L8NE0-F01C1MGMP0D/image.png

**Comment by brandongregoryscott** [comment]
@KevinBusch Just stumbled upon this - I think this might be a limitation of our node version. Since `5.0.0` they require node 10+:

https://github.com/cypress-io/cypress/releases/tag/v5.0.0

@dylanjustice Recently queried the team about projects still leveraging older node versions so we can update our Jenkins instance, or possibly spin up another VM to leverage a newer node version. Going to close this out for now since it is not directly related to this package.

**Comment by dylanjustice** [comment]
@brandongregoryscott  Should I link the slack message where @KevinBusch trolled my question?
